export const Globals  = {
    RESPONSE_OK : '200',
    RESPONSE_CREATED : '201',
    RESONSE_NO_CONTENT : '204',
    RESPONSE_BAD_REQUEST : '400',
    RESPONSE_UNAUTHORIZED : '401',
    RESPONSE_FORBIDDEN : '403',
    RESPONSE_NOT_FOUND : '404',
    RESPONSE_INTERNAL_SERVER_ERROR : '500',

    CATALOG_PARAMETROS : 'parametros',
    CATALOG_CONFIG : 'config',
    CATALOG_CATALOGOS : 'catalogos',
    CATALOG_CLIENTES : 'clientes',
    CATALOG_ARTICULOS : 'articulos',
	CATALOG_TTABLAS : 'ttablas',
	CATALOG_TMP_CLIENTES : 'tmpCliente',
	CATALOG_CONFIG_SETUP : 'configSetup',
	CATALOG_SESSION : 'session',
	CATALOG_PEDIDO_CABECERA : 'pedidoCabecera',
	CATALOG_PEDIDO_DETALLE : 'pedidoDetalle',

	IS_RUTA : '1',

	ESTADO_PEDIDO : {
		GRABADO : '',
		ANULADO : 'A'
	},
	ESTADO_PEDIDO_ENVIO : {
		PENDIENTE : 'P',
		ENVIADO : 'T'
	},
	ESTADO_CLIENTE : {
		ATENDIDO : 'A',
		MOTIVO_NO_ATENCION : 'N'
	},
	// SERVER
	MODO_LOCAL : 'LOCAL',
	MODO_HOSTING : 'HOSTING',
	MODO_SERVER : 'HOSTING',
	LOCAL_SERVER : 'http://127.0.0.1/demopvta/api/',
	HOSTING_SERVER : 'https://ismytv.webcindario.com/api/',
	USER_ROOT : 'root',
	PASSWORD_ROOT : 'alice1234567',

    // CODIGOS DE TABLA (tTablas)
	CODTABLA_TIPOS_DOCUMENTO : "01",
	CODTABLA_MONEDAS : "02",
	CODTABLA_UNIDADES_MEDIDA : "03",
	CODTABLA_TIPOS_DOCIDEN : "06",
	CODTABLA_TIPOS_AFECTACION : "07",
	CODTABLA_TIPOS_CALCULO_ISC : "??",
	CODTABLA_FORMAS_PAGO : "90",
	CODTABLA_TIPBUSART : "91",
	CODTABLA_TIPOS_PERSONA : "92",
	CODTABLA_TIPOS_SEXO : "93",
	CODTABLA_TIPOS_DESCUENTO : "94",
	// 
	TIPO_DNI : "1",
	TIPO_RUC : "6",
	//
	TIPO_FACTURA : "01",
	TIPO_BOLETA : "03",
	//
	TIPO_PERSONA_NATURAL : "01",
	TIPO_PERSONA_JURIDICA : "02",
	//
	PRODUCTO_AFECTO_IGV : "10",
	IGV_INCLUIDO_EN_PRECIO : false,
	//
	FORMA_PAGO_EFECTIVO : "01",
	TIPO_DESCUENTO_PORCENTAJE : "01"
};
